version: '3.0'

services:

  redis:
    image: redis:latest
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always
  

  db:
   image: postgres
   environment:
       POSTGRES_USER: Godwin
       POSTGRES_PASSWORD: secret
   ports:
     - 5432:5432      
   volumes:
      - postgres-data:/data
    

   

volumes:
  redis-data:
  postgres-data:

